version: '3.8'

services:
  flask-app:
    image: joseantoniocgonzalez/flask-app
    container_name: flask-app
    ports:
      - "5002:5002"
    environment:
      - NOMBRE=JoseAntonio
    restart: always
